# Site settings
title: darkshredder Blogs # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/darkshredder" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: assets/img/hacker.gif # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/darkshredder/my-blogs # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: darkshredder # author name
  bio: >- # tell to the world
    A developer trying to convey his thoughts and learnings through <a href="https://github.com/darkshredder/my-blogs" target="_blank" rel="noopener">@github</a>.
  username: darkshredder # general username
  github: darkshredder # github username
  twitter: __darkshredder__ # twitter username
  facebook: yash.srivastava.9887 # facebook username
  email: contact@darkshredder.com # email adress
  avatar: /assets/img/avatar.jpeg # change with your own avatar

# URL settings
url: "https://darkshredder.codes" #
baseurl:
permalink: /:title/
google_analytics: UA-237522785-2
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: darkshredder
remote_theme: jekyll/minima
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - darkshredder-*.gem
  - darkshredder.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-remote-theme
